# Generated by Django 5.1 on 2024-09-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BankTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=50)),
                ("iban", models.CharField(max_length=10)),
                ("account_number", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Bank Transfer",
                "verbose_name_plural": "Bank Transfers",
            },
        ),
        migrations.CreateModel(
            name="CryptoTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wallet_address", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Crypto Transfer",
                "verbose_name_plural": "Crypto Transfers",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
            },
        ),
        migrations.CreateModel(
            name="PayPalTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paypal_email", models.EmailField(max_length=255)),
            ],
            options={
                "verbose_name": "PayPal Transfer",
                "verbose_name_plural": "PayPal Transfers",
            },
        ),
        migrations.CreateModel(
            name="PrepaidTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Prepaid Transfer",
                "verbose_name_plural": "Prepaid Transfers",
            },
        ),
    ]
