# Generated by Django 5.1 on 2024-10-02 13:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
            },
        ),
        migrations.CreateModel(
            name="CryptoCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=10, null=True, unique=True)),
            ],
            options={
                "verbose_name": "Crypto Currency",
                "verbose_name_plural": "Crypto Currencies",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("description", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                            ("Canceled", "Canceled"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankTransfer",
            fields=[
                (
                    "paymentmethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.paymentmethod",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("iban", models.CharField(max_length=10)),
                ("swift", models.CharField(max_length=20, null=True)),
                (
                    "account_number",
                    models.CharField(max_length=50, null=True, unique=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank Transfer",
                "verbose_name_plural": "Bank Transfers",
            },
            bases=("payments.paymentmethod",),
        ),
        migrations.CreateModel(
            name="CryptoTransfer",
            fields=[
                (
                    "paymentmethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                (
                    "cryptocurrency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.cryptocurrency",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Crypto Transfer",
                "verbose_name_plural": "Crypto Transfers",
            },
            bases=("payments.paymentmethod",),
        ),
        migrations.CreateModel(
            name="PayPalTransfer",
            fields=[
                (
                    "paymentmethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "paypal_email",
                    models.EmailField(max_length=255, null=True, unique=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PayPal Transfer",
                "verbose_name_plural": "PayPal Transfers",
            },
            bases=("payments.paymentmethod",),
        ),
        migrations.CreateModel(
            name="PrepaidTransfer",
            fields=[
                (
                    "paymentmethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.paymentmethod",
                    ),
                ),
                ("owner_name", models.CharField(max_length=255, null=True)),
                (
                    "card_number",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("expiration_date", models.DateField(null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prepaid Transfer",
                "verbose_name_plural": "Prepaid Transfers",
            },
            bases=("payments.paymentmethod",),
        ),
    ]
