# Generated by Django 5.1 on 2024-09-27 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
            },
        ),
        migrations.CreateModel(
            name="BankTransfer",
            fields=[
                (
                    "paymentmethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.paymentmethod",
                    ),
                ),
                ("bank_name", models.CharField(max_length=50)),
                ("iban", models.CharField(max_length=10)),
                ("account_number", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Bank Transfer",
                "verbose_name_plural": "Bank Transfers",
            },
            bases=("payments.paymentmethod",),
        ),
        migrations.CreateModel(
            name="CryptoTransfer",
            fields=[
                (
                    "paymentmethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.paymentmethod",
                    ),
                ),
                ("wallet_address", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Crypto Transfer",
                "verbose_name_plural": "Crypto Transfers",
            },
            bases=("payments.paymentmethod",),
        ),
        migrations.CreateModel(
            name="PayPalTransfer",
            fields=[
                (
                    "paymentmethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.paymentmethod",
                    ),
                ),
                ("paypal_email", models.EmailField(max_length=255)),
            ],
            options={
                "verbose_name": "PayPal Transfer",
                "verbose_name_plural": "PayPal Transfers",
            },
            bases=("payments.paymentmethod",),
        ),
        migrations.CreateModel(
            name="PrepaidTransfer",
            fields=[
                (
                    "paymentmethod_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="payments.paymentmethod",
                    ),
                ),
                ("card_number", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Prepaid Transfer",
                "verbose_name_plural": "Prepaid Transfers",
            },
            bases=("payments.paymentmethod",),
        ),
    ]
