# Generated by Django 5.1 on 2024-09-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransfer",
            name="account_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="cryptotransfer",
            name="wallet_address",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(
                choices=[
                    ("Bank Transfer", "Bank Transfer"),
                    ("Prepaid", "Prepaid"),
                    ("PayPal", "PayPal"),
                    ("Crypto", "Crypto"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paypaltransfer",
            name="paypal_email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="prepaidtransfer",
            name="card_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
