# Generated by Django 5.1 on 2024-10-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransfer",
            name="bank_name",
            field=models.CharField(max_length=255),
        ),
    ]
