# Generated by Django 5.1 on 2024-09-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_remove_invoicedetails_payment_method"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="PaymentMethod",),
    ]
