# Generated by Django 5.1 on 2024-09-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_banktransfer_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
