# Generated by Django 5.1 on 2024-09-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_paymentmethod_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="user_uuid",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
