# Generated by Django 5.1 on 2024-09-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_paymentmethod_user_uuid"),
    ]

    operations = [
        migrations.RemoveField(model_name="paymentmethod", name="user_uuid",),
    ]
