# Generated by Django 5.1 on 2024-09-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_remove_paymentmethod_user_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
