# Generated by Django 5.1 on 2024-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_cryptocurrency_remove_paymentmethod_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cryptocurrency",
            options={
                "verbose_name": "Crypto Currency",
                "verbose_name_plural": "Crypto Currencies",
            },
        ),
        migrations.AddField(
            model_name="banktransfer",
            name="swift",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
