# Generated by Django 5.1 on 2024-09-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_alter_cryptocurrency_options_banktransfer_swift"),
    ]

    operations = [
        migrations.AddField(
            model_name="prepaidtransfer",
            name="expiration_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="prepaidtransfer",
            name="owner_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
