# Generated by Django 5.1 on 2024-09-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
