# Generated by Django 5.1 on 2024-09-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_cryptotransfer_user_paypaltransfer_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransfer",
            name="bank_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
