# Generated by Django 5.1 on 2024-09-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0015_alter_banktransfer_bank_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptotransfer",
            name="wallet_address",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
