from .base import *
import os

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

STATIC_URL = "/static/"
MEDIA_URL = "/media/"

STATIC_ROOT = ""
MEDIA_ROOT = ""

SECURE_HSTS_SECONDS = 500000
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
