# Generated by Django 5.1 on 2024-10-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
        migrations.AddField(
            model_name="company",
            name="name",
            field=models.CharField(default="Elegance Hair Studio", max_length=100),
        ),
    ]
