# Generated by Django 5.1 on 2024-10-02 13:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeTaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=10, unique=True),
                ),
            ],
            options={
                "verbose_name": "Income Tax",
                "verbose_name_plural": "Income Taxes",
            },
        ),
        migrations.CreateModel(
            name="InvoiceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("file", models.FileField(upload_to="invoices/invoices")),
                ("size", models.IntegerField(null=True)),
                ("format", models.CharField(max_length=3)),
            ],
            options={
                "verbose_name": "Invoice File",
                "verbose_name_plural": "Invoices Files",
            },
        ),
        migrations.CreateModel(
            name="InvoiceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Invoice Status",
                "verbose_name_plural": "Invoice Statuses",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "invoice_number",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                (
                    "description_of_product_or_services",
                    models.CharField(max_length=1000, null=True),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "gross_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("payment_due_date", models.DateField(null=True)),
                (
                    "buyer_details",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "income_tax",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.incometaxrate",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.paymentmethod",
                    ),
                ),
                (
                    "seller_details",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.company",
                    ),
                ),
                (
                    "invoice_file",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invoices.invoicefile",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="invoices.invoicestatus",
                    ),
                ),
            ],
            options={"verbose_name": "Invoice", "verbose_name_plural": "Invoices",},
        ),
    ]
