# Generated by Django 5.1 on 2024-09-27 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoicedetails",
            name="payment_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payments.paymentmethod"
            ),
        ),
        migrations.RemoveField(model_name="invoicedetails", name="payment_terms",),
        migrations.DeleteModel(name="PaymentMethod",),
        migrations.DeleteModel(name="PaymentTerms",),
    ]
