# Generated by Django 5.1 on 2024-10-01 14:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_profile_employment_information_and_more"),
        ("core", "0001_initial"),
        ("invoices", "0001_initial"),
        ("payments", "0017_cryptocurrency_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeTaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, max_digits=4, unique=True),
                ),
            ],
            options={
                "verbose_name": "Income Tax",
                "verbose_name_plural": "Income Taxes",
            },
        ),
        migrations.CreateModel(
            name="InvoiceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("file", models.FileField(upload_to="invoices/invoices")),
                ("format", models.CharField(max_length=3)),
            ],
            options={
                "verbose_name": "Invoice File",
                "verbose_name_plural": "Invoices Files",
            },
        ),
        migrations.RemoveField(model_name="invoicedetails", name="buyers_details",),
        migrations.RemoveField(model_name="invoicedetails", name="sellers_details",),
        migrations.RemoveField(model_name="invoicedetails", name="vat_rate",),
        migrations.RemoveField(model_name="invoice", name="invoice_details",),
        migrations.RemoveField(model_name="invoice", name="file",),
        migrations.AddField(
            model_name="invoice",
            name="buyers_details",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="description_of_product_or_services",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="gross_amount",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="issue_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="invoice",
            name="net_amount",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_due_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="invoice", name="quantity", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sellers_details",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.company",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="unit_net_price",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vat_amount",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="income_tax",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invoices.incometaxrate",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="invoice_file",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invoices.invoicefile",
            ),
        ),
        migrations.DeleteModel(name="VatRate",),
        migrations.DeleteModel(name="InvoiceDetails",),
    ]
