# Generated by Django 5.1 on 2024-09-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_alter_invoicedetails_payment_method_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoicedetails", name="payment_method",),
    ]
