# Generated by Django 5.1 on 2024-10-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_incometaxrate_invoicefile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicefile", name="size", field=models.IntegerField(null=True),
        ),
    ]
