# Generated by Django 5.1 on 2024-10-01 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_invoicefile_size"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice", old_name="unit_net_price", new_name="tax_amount",
        ),
        migrations.RemoveField(model_name="invoice", name="vat_amount",),
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
