# Generated by Django 5.1 on 2024-10-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_rename_unit_net_price_invoice_tax_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice", old_name="buyers_details", new_name="buyer_details",
        ),
        migrations.RenameField(
            model_name="invoice", old_name="sellers_details", new_name="seller_details",
        ),
        migrations.AlterField(
            model_name="incometaxrate",
            name="rate",
            field=models.DecimalField(decimal_places=2, max_digits=10, unique=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="gross_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="net_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
