# Generated by Django 5.1 on 2024-10-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0005_rename_buyers_details_invoice_buyer_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoice", name="quantity",),
    ]
