# Generated by Django 5.1 on 2024-10-01 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0006_remove_invoice_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_file",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoices.invoicefile",
            ),
        ),
    ]
