# Generated by Django 5.1 on 2024-10-01 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0012_alter_invoice_buyer_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
