# Generated by Django 5.1 on 2024-10-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contracttype",
            name="slug",
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
