# Generated by Django 5.1 on 2024-10-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contracttype_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposition",
            name="slug",
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
