# Generated by Django 5.1 on 2024-09-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_contract_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="time_remaining",
            field=models.DurationField(null=True),
        ),
    ]
