# Generated by Django 5.1 on 2024-10-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_employmentstatus_slug_paymentfrequency_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="currency",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
