# Generated by Django 5.1 on 2024-10-01 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_contract_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="job_position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contracts.jobposition",
            ),
        ),
    ]
