# Generated by Django 5.1 on 2024-10-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_contract_job_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="total_invoices",
            field=models.IntegerField(null=True),
        ),
    ]
