# Generated by Django 5.1 on 2024-10-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_currency_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="salarybenefit", name="period",),
        migrations.RemoveField(model_name="benefit", name="salary_benefits",),
        migrations.DeleteModel(name="SalaryPeriod",),
        migrations.DeleteModel(name="SalaryBenefit",),
    ]
