# Generated by Django 5.1 on 2024-10-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0007_remove_salarybenefit_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentbenefit",
            name="slug",
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="healthbenefit",
            name="slug",
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="insurancebenefit",
            name="slug",
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="sportbenefit",
            name="slug",
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
