# Generated by Django 5.1 on 2024-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0007_contract_total_invoices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="total_invoices",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
