# Generated by Django 5.1 on 2024-10-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0008_alter_contract_total_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="total_earnings",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
