# Generated by Django 5.1 on 2024-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0009_contract_total_earnings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="total_earnings",
            new_name="total_earnings_gross",
        ),
        migrations.AddField(
            model_name="contract",
            name="total_earnings_net",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
