# Generated by Django 5.1 on 2024-10-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contracts",
            "0010_rename_total_earnings_contract_total_earnings_gross_and_more",
        ),
        ("invoices", "0010_alter_invoice_invoice_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="invoices",
            field=models.ManyToManyField(to="invoices.invoice"),
        ),
    ]
