# Generated by Django 5.1 on 2024-11-20 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.CharField()),
                ("duration", models.PositiveIntegerField()),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0.23, max_digits=5),
                ),
                ("net_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("gross_price", models.DecimalField(decimal_places=2, max_digits=2)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.servicecategory",
                    ),
                ),
            ],
        ),
    ]
