# Generated by Django 5.1 on 2024-11-20 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Service", "verbose_name_plural": "Services"},
        ),
        migrations.AlterModelOptions(
            name="servicecategory",
            options={
                "verbose_name": "Service Category",
                "verbose_name_plural": "Service Categories",
            },
        ),
    ]
