# Generated by Django 5.1 on 2024-11-20 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_service_options_alter_servicecategory_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceTaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0.23, max_digits=4),
                ),
            ],
            options={
                "verbose_name": "Service Tax Rate",
                "verbose_name_plural": "Services Tax Rate",
            },
        ),
        migrations.RemoveField(model_name="service", name="employee",),
        migrations.AddField(
            model_name="service",
            name="employees",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.servicecategory",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="tax_rate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.servicetaxrate",
            ),
        ),
    ]
