# Generated by Django 5.1 on 2024-11-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_servicetaxrate_remove_service_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="gross_price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
