# Generated by Django 5.1 on 2024-11-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_alter_service_gross_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
