# Generated by Django 5.1 on 2024-11-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_alter_service_description_alter_service_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service", name="description", field=models.TextField(),
        ),
    ]
