# Generated by Django 5.1 on 2024-12-05 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_serviceimage_service_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="services.serviceimage",
            ),
        ),
    ]
