# Generated by Django 5.1 on 2024-09-25 20:39

import accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Contract Type",
                "verbose_name_plural": "Contract Types",
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={"verbose_name": "Currency", "verbose_name_plural": "Currencies",},
        ),
        migrations.CreateModel(
            name="DevelopmentBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Development Benefit",
                "verbose_name_plural": "Development Benefits",
            },
        ),
        migrations.CreateModel(
            name="EmploymentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Employment Status",
                "verbose_name_plural": "Employment Statuses",
            },
        ),
        migrations.CreateModel(
            name="HealthBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Health Benefit",
                "verbose_name_plural": "Health Benefits",
            },
        ),
        migrations.CreateModel(
            name="InsuranceBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Insurance Benefit",
                "verbose_name_plural": "Insurance Benefits",
            },
        ),
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Job Position",
                "verbose_name_plural": "Job Positions",
            },
        ),
        migrations.CreateModel(
            name="JobType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={"verbose_name": "Job Type", "verbose_name_plural": "Job Types",},
        ),
        migrations.CreateModel(
            name="PaymentFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Payment Frequency",
                "verbose_name_plural": "Payments Frequency",
            },
        ),
        migrations.CreateModel(
            name="ProfileContactInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, null=True, unique=True),
                ),
                ("country", models.CharField(max_length=100, null=True)),
                ("province", models.CharField(max_length=100, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("postal_code", models.CharField(max_length=100, null=True)),
                ("street", models.CharField(max_length=100, null=True)),
                ("house_number", models.CharField(max_length=10, null=True)),
                (
                    "apartment_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "verbose_name": "Profile Contact Information",
                "verbose_name_plural": "Profile Contact Information",
            },
        ),
        migrations.CreateModel(
            name="ProfileImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        default="accounts/profile_images/default_profile_image.png",
                        null=True,
                        upload_to="accounts/profile_images",
                    ),
                ),
                ("size", models.IntegerField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("height", models.IntegerField(null=True)),
                ("format", models.CharField(max_length=100, null=True)),
                ("alt", models.CharField(max_length=1000, null=True)),
            ],
            options={
                "verbose_name": "Profile Image",
                "verbose_name_plural": "Profile Images",
            },
        ),
        migrations.CreateModel(
            name="SalaryBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_award", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Benefit",
                "verbose_name_plural": "Salary Benefits",
            },
        ),
        migrations.CreateModel(
            name="SalaryPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Salary Period",
                "verbose_name_plural": "Salary Periods",
            },
        ),
        migrations.CreateModel(
            name="SportBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Sport Benefit",
                "verbose_name_plural": "Sport Benefits",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "username",
                    models.CharField(default=uuid.uuid4, max_length=1000, unique=True),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"verbose_name": "Account", "verbose_name_plural": "Accounts",},
            managers=[("objects", accounts.models.CustomUserManager()),],
        ),
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "development_benefits",
                    models.ManyToManyField(to="accounts.developmentbenefit"),
                ),
                (
                    "health_benefits",
                    models.ManyToManyField(to="accounts.healthbenefit"),
                ),
                (
                    "insurance_benefits",
                    models.ManyToManyField(to="accounts.insurancebenefit"),
                ),
                (
                    "job_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.jobtype",
                    ),
                ),
                (
                    "salary_benefits",
                    models.ManyToManyField(to="accounts.salarybenefit"),
                ),
                ("sport_benefits", models.ManyToManyField(to="accounts.sportbenefit")),
            ],
            options={"verbose_name": "Benefit", "verbose_name_plural": "Benefits",},
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("work_hours_per_week", models.IntegerField(blank=True, null=True)),
                (
                    "benefits",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.benefit",
                    ),
                ),
                (
                    "contract_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.contracttype",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.currency",
                    ),
                ),
                (
                    "job_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.jobtype",
                    ),
                ),
            ],
            options={"verbose_name": "Contract", "verbose_name_plural": "Contracts",},
        ),
        migrations.CreateModel(
            name="OneTimePassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("password", models.CharField(max_length=6, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "One Time Password",
                "verbose_name_plural": "One Time Passwords",
            },
        ),
        migrations.CreateModel(
            name="ProfileEmploymentInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.contract",
                    ),
                ),
                (
                    "employment_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.employmentstatus",
                    ),
                ),
                (
                    "job_position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.jobposition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Employment Information",
                "verbose_name_plural": "Profile Employment Information",
            },
        ),
        migrations.CreateModel(
            name="ProfileBasicInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=200)),
                ("lastname", models.CharField(max_length=200)),
                ("biography", models.TextField(max_length=10000, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "profile_image",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profileimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Basic Information",
                "verbose_name_plural": "Profile Basic Information",
            },
        ),
        migrations.CreateModel(
            name="ProfilePaymentInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iban", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "payment_frequency",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.paymentfrequency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Information",
                "verbose_name_plural": "Payments Information",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "basic_information",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profilebasicinformation",
                    ),
                ),
                (
                    "contact_information",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profilecontactinformation",
                    ),
                ),
                (
                    "employment_information",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profileemploymentinformation",
                    ),
                ),
                (
                    "payment_information",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.profilepaymentinformation",
                    ),
                ),
            ],
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles",},
        ),
        migrations.AddField(
            model_name="salarybenefit",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.salaryperiod",
            ),
        ),
    ]
