# Generated by Django 5.1 on 2024-09-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="payment_information",),
        migrations.DeleteModel(name="ProfilePaymentInformation",),
    ]
