# Generated by Django 5.1 on 2024-09-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract", name="name", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employmentstatus",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="jobposition",
            name="name",
            field=models.CharField(
                choices=[
                    ("Owner", "Owner"),
                    ("Manager", "Manager"),
                    ("Receptionist", "Receptionist"),
                    ("Hairstylist", "Hairstylist"),
                    ("Assistant", "Assistant"),
                    ("Barber", "Barber"),
                ],
                max_length=200,
            ),
        ),
    ]
