# Generated by Django 5.1 on 2024-10-02 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="contract",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contracts.contract",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="basic_information",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profilebasicinformation",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="contact_information",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profilecontactinformation",
            ),
        ),
        migrations.AddField(
            model_name="profilebasicinformation",
            name="profile_image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.profileimage",
            ),
        ),
    ]
