# Generated by Django 4.2.16 on 2024-09-13 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profileimage_options_profile_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="dateofbirth",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
