# Generated by Django 5.1 on 2024-10-01 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_profileemploymentinformation_employment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profileemploymentinformation", name="job_position",
        ),
    ]
