# Generated by Django 5.1 on 2024-09-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_contract_name_alter_employmentstatus_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="name",
            field=models.CharField(
                choices=[
                    ("Employment Contract", "Employment Contract"),
                    ("Contract of Mandate", "Contract of Mandate"),
                    ("Contract for Specific Work", "Contract for Specific Work"),
                    ("B2B", "B2B"),
                    ("Agency Contract", "Agency Contract"),
                    ("Internship Contract", "Internship Contract"),
                    ("Temporary Employment Contract", "Temporary Employment Contract"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="employmentstatus",
            name="name",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("On Leave", "On Leave"),
                ],
                max_length=100,
            ),
        ),
    ]
