# Generated by Django 5.1 on 2024-09-24 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_contract_name_alter_employmentstatus_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("Monthly", "Monthly"), ("Weekly", "Weekly")],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Frequency",
                "verbose_name_plural": "Payments Frequency",
            },
        ),
        migrations.CreateModel(
            name="ProfilePaymentInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.IntegerField(blank=True, null=True)),
                (
                    "payment_frequency",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.paymentfrequency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Information",
                "verbose_name_plural": "Payments Information",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="payment_information",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profilepaymentinformation",
            ),
        ),
    ]
