# Generated by Django 5.1 on 2024-10-01 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_profile_employment_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilebasicinformation",
            name="profile_image",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.profileimage",
            ),
        ),
    ]
