# Generated by Django 5.1 on 2024-09-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_paymentfrequency_profilepaymentinformation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilepaymentinformation",
            name="iban",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
