# Generated by Django 5.1 on 2024-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profilepaymentinformation_iban"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilepaymentinformation",
            name="account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
