# Generated by Django 5.1 on 2024-09-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_onetimepassword_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onetimepassword",
            name="password",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
