# Generated by Django 5.1 on 2024-09-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_onetimepassword_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="apartment_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="biography",
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="country",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_of_employment",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("On Leave", "On Leave"),
                    ("Inactive", "Inactive"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="house_number",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="province",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="street",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
