# Generated by Django 5.1 on 2024-09-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_profile_apartment_number_profile_biography_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="apartment_number",
            new_name="apartmentnumber",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="date_of_employment",
            new_name="dateofemployment",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="employment_status",
            new_name="employmentstatus",
        ),
        migrations.RenameField(
            model_name="profile", old_name="house_number", new_name="housenumber",
        ),
        migrations.RenameField(
            model_name="profile", old_name="phone_number", new_name="phonenumber",
        ),
        migrations.RenameField(
            model_name="profile", old_name="profile_image", new_name="profileimage",
        ),
        migrations.RenameField(
            model_name="profile", old_name="user_type", new_name="usertype",
        ),
    ]
