# Generated by Django 5.1 on 2024-09-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_rename_apartment_number_profile_apartmentnumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dateofemployment",
            field=models.DateField(blank=True, null=True),
        ),
    ]
