# Generated by Django 5.1 on 2024-09-18 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_profile_dateofemployment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileContactInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phonenumber", models.CharField(max_length=20, null=True)),
                ("country", models.CharField(max_length=100, null=True)),
                ("province", models.CharField(max_length=100, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("street", models.CharField(max_length=100, null=True)),
                ("housenumber", models.CharField(max_length=10, null=True)),
                (
                    "apartmentnumber",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "verbose_name": "Profile Contact Information",
                "verbose_name_plural": "Profile Contact Information",
            },
        ),
        migrations.CreateModel(
            name="ProfileEmploymentInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usertype",
                    models.CharField(
                        choices=[
                            ("Owner", "Owner"),
                            ("Manager", "Manager"),
                            ("Receptionist", "Receptionist"),
                            ("Hairstylist", "Hairstylist"),
                            ("Assistant", "Assistant"),
                            ("Barber", "Barber"),
                            ("Not Defined", "Not Defined"),
                        ],
                        default="Not Defined",
                        max_length=200,
                    ),
                ),
                ("dateofemployment", models.DateField(blank=True, null=True)),
                (
                    "employmentstatus",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("On Leave", "On Leave"),
                            ("Inactive", "Inactive"),
                        ],
                        default="Active",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Employment Information",
                "verbose_name_plural": "Profile Employment Information",
            },
        ),
        migrations.RemoveField(model_name="profile", name="apartmentnumber",),
        migrations.RemoveField(model_name="profile", name="biography",),
        migrations.RemoveField(model_name="profile", name="city",),
        migrations.RemoveField(model_name="profile", name="country",),
        migrations.RemoveField(model_name="profile", name="dateofbirth",),
        migrations.RemoveField(model_name="profile", name="dateofemployment",),
        migrations.RemoveField(model_name="profile", name="employmentstatus",),
        migrations.RemoveField(model_name="profile", name="firstname",),
        migrations.RemoveField(model_name="profile", name="housenumber",),
        migrations.RemoveField(model_name="profile", name="lastname",),
        migrations.RemoveField(model_name="profile", name="phonenumber",),
        migrations.RemoveField(model_name="profile", name="profileimage",),
        migrations.RemoveField(model_name="profile", name="province",),
        migrations.RemoveField(model_name="profile", name="street",),
        migrations.RemoveField(model_name="profile", name="usertype",),
        migrations.CreateModel(
            name="ProfileBasicInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=200)),
                ("lastname", models.CharField(max_length=200)),
                ("biography", models.TextField(max_length=10000, null=True)),
                ("dateofbirth", models.DateField(blank=True, null=True)),
                (
                    "profileimage",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.profileimage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Basic Information",
                "verbose_name_plural": "Profile Basic Information",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="basicinformation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.profilebasicinformation",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="contactinformation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.profilecontactinformation",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="employmentinformation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.profileemploymentinformation",
            ),
        ),
    ]
