# Generated by Django 5.1 on 2024-09-18 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_profilecontactinformation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="basicinformation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profilebasicinformation",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="contactinformation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profilecontactinformation",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="employmentinformation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profileemploymentinformation",
            ),
        ),
        migrations.AlterField(
            model_name="profilebasicinformation",
            name="profileimage",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profileimage",
            ),
        ),
    ]
