# Generated by Django 5.1 on 2024-09-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_profile_basicinformation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilecontactinformation",
            name="postalcode",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
