# Generated by Django 5.1 on 2024-09-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0015_rename_dateofbirth_profilebasicinformation_date_of_birth_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="profilecontactinformation",
            old_name="apartmentnumber",
            new_name="apartment_number",
        ),
        migrations.RenameField(
            model_name="profilecontactinformation",
            old_name="housenumber",
            new_name="house_number",
        ),
        migrations.RenameField(
            model_name="profilecontactinformation",
            old_name="phonenumber",
            new_name="phone_number",
        ),
        migrations.RenameField(
            model_name="profilecontactinformation",
            old_name="postalcode",
            new_name="postal_code",
        ),
    ]
