# Generated by Django 5.1 on 2024-09-23 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0016_rename_apartmentnumber_profilecontactinformation_apartment_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Job Position",
                "verbose_name_plural": "Job Positions",
            },
        ),
        migrations.RemoveField(
            model_name="profileemploymentinformation", name="usertype",
        ),
        migrations.AddField(
            model_name="profileemploymentinformation",
            name="job_position",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.jobposition",
            ),
        ),
    ]
