# Generated by Django 5.1 on 2024-09-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_jobposition_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profileemploymentinformation",
            old_name="dateofemployment",
            new_name="date_of_employment",
        ),
        migrations.AlterField(
            model_name="profileemploymentinformation",
            name="job_position",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.jobposition",
            ),
        ),
    ]
