# Generated by Django 5.1 on 2024-09-23 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0018_rename_dateofemployment_profileemploymentinformation_date_of_employment_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmploymentStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Inactive", max_length=100)),
            ],
            options={
                "verbose_name": "Employment Status",
                "verbose_name_plural": "Employment Statuses",
            },
        ),
        migrations.RemoveField(
            model_name="profileemploymentinformation", name="employmentstatus",
        ),
        migrations.AddField(
            model_name="profileemploymentinformation",
            name="employment_status",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.employmentstatus",
            ),
        ),
    ]
