# Generated by Django 5.1 on 2024-09-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_employmentstatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposition",
            name="name",
            field=models.CharField(default="Not Defined", max_length=200),
        ),
    ]
