# Generated by Django 5.1 on 2024-09-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_jobposition_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Not Defined", max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("work_hours_per_week", models.IntegerField(blank=True, null=True)),
            ],
            options={"verbose_name": "Contract", "verbose_name_plural": "Contracts",},
        ),
        migrations.RemoveField(
            model_name="profileemploymentinformation", name="contractduration",
        ),
        migrations.RemoveField(
            model_name="profileemploymentinformation", name="contractenddate",
        ),
        migrations.RemoveField(
            model_name="profileemploymentinformation", name="contractstartdate",
        ),
        migrations.RemoveField(
            model_name="profileemploymentinformation", name="contracttype",
        ),
        migrations.RemoveField(
            model_name="profileemploymentinformation", name="date_of_employment",
        ),
        migrations.RemoveField(
            model_name="profileemploymentinformation", name="salary",
        ),
        migrations.RemoveField(
            model_name="profileemploymentinformation", name="work_hours_per_week",
        ),
        migrations.AddField(
            model_name="profileemploymentinformation",
            name="contract",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.contract",
            ),
        ),
    ]
