# Generated by Django 4.2.16 on 2024-09-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("Employee", "Employee"), ("Employer", "Employer")],
                default="Employee",
                max_length=100,
            ),
        ),
    ]
